trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - "*"

stages:
  - stage: CI
    displayName: "CI on PR"
    jobs:
      - job: PR_Validation
        displayName: "Terraform Validation on PR"
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'AzureARMPersonalAccount'
              scriptType: 'bash'
              addSpnToEnvironment: true
              useGlobalConfig: true
              scriptLocation: 'inlineScript'
              inlineScript: |
                az account show
                echo "##vso[task.setvariable variable=ARM_CLIENT_ID]$(az account get-access-token --query accessToken -o tsv)"
                echo "##vso[task.setvariable variable=ARM_CLIENT_SECRET]$(az account get-access-token --query tokenType -o tsv)"
                echo "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID]$(az account show --query id -o tsv)"
                echo "##vso[task.setvariable variable=ARM_TENANT_ID]$(az account show --query tenantId -o tsv)"
              displayName: "Azure CLI Login"

          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'AzureARMPersonalAccount'
              backendAzureRmResourceGroupName: 'beStrongTfState'
              backendAzureRmStorageAccountName: 'backendaccount304'
              backendAzureRmContainerName: 'tfstatebestrong'
              backendAzureRmKey: 'beststrong.tfstate'

          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'validate'

          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: 'AzureARMPersonalAccount'
