trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - "*"

stages:
  - stage: CI
    displayName: "CI on PR"
    jobs:
      - job: PR_Validation
        displayName: "Terraform Validation on PR"
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
          - script: apt update & apt install terraform
            displayName: "Install Terraform"
              
          - script: terraform init
            displayName: "Terraform Init"

          - script: terraform validate
            displayName: "Terraform Validate"

          - script: terraform plan -out=tfplan
            displayName: "Terraform Plan"
