trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - "*"

stages:
  - stage: CI
    displayName: "CI on PR"
    jobs:
      - job: PR_Validation
        displayName: "Terraform Validation on PR"
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'AzureARMPersonalAccount'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az account show
                echo "##vso[task.setvariable variable=ARM_CLIENT_ID]$(az account get-access-token --query accessToken -o tsv)"
                echo "##vso[task.setvariable variable=ARM_CLIENT_SECRET]$(az account get-access-token --query tokenType -o tsv)"
                echo "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID]$(az account show --query id -o tsv)"
                echo "##vso[task.setvariable variable=ARM_TENANT_ID]$(az account show --query tenantId -o tsv)"
              displayName: "Azure CLI Login"

          - task: TerraformInstaller@0
            inputs:
              terraformVersion: 'latest'
              
          - script: terraform init
            displayName: "Terraform Init"

          - script: terraform validate
            displayName: "Terraform Validate"

          - script: terraform plan -out=tfplan
            displayName: "Terraform Plan"
