variables:
- group: terrafrom_var
- group: Azure

stages:
  - stage: destroy
    displayName: "Terraform destroy on PR"
    jobs:
      - job: PR_Plan
        displayName: "Terraform Destroyn on PR"
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: $(ServiceConnection)
              backendAzureRmResourceGroupName: $(backendGroup)
              backendAzureRmStorageAccountName: $(backendStorage)
              backendAzureRmContainerName: $(backendContainer)
              backendAzureRmKey: $(backendKey)
            displayName: "Terraform Init"

          - task: AzureCLI@2
                inputs:
                  azureSubscription: $(ServiceConnection)
                  scriptType: 'bash'
                  scriptLocation: 'inlineScript'
                  inlineScript: |
                    MY_IP=$(curl -s ifconfig.me)
                    az storage account network-rule add \
                      --resource-group "beStrongApp" \
                      --account-name "beststrongstorage02" \
                      --ip-address $MY_IP
                    az keyvault network-rule add \
                      --resource-group "beStrongApp" \
                      --name "kv-bestrong" \
                      --ip-address $MY_IP
                  displayName: "Fix firewall rule"

          - task: TerraformTaskV4@4
                inputs:
                  provider: 'azurerm'
                  command: 'destroy'
                  environmentServiceNameAzureRM: $(ServiceConnection)
                  commandOptions: '-auto-approve'
                displayName: "Terraform Destroy"
                env:
                  TF_VAR_login_for_sql: $(TF_VAR_login_for_sql)
                  TF_VAR_password_for_sql: $(TF_VAR_password_for_sql)
                  TF_VAR_org_ip: $(TF_VAR_org_ip)